### ISSUE TITLE
It's not blocking new taps

### ISSUE THREAD

**Issue by bensmithgb53** [MarcellPerger1/adblock-bookmarklet#33] opened 2024-01-03 18:02 UTC
When I go to a website and click on a link/anywhere on that website it opens a new to tap to malicious ad/betting ad. This there anyway to stop this from happening please? I get theses ads pop up alot on websites and would be handy to have this.

**Comment by MarcellPerger1** [comment] 2024-02-26 19:15
Duplicate of #31

**Closed by MarcellPerger1** 2024-02-26 19:15 UTC
Labels: duplicate
