### ISSUE TITLE
Bookmarklet redirects away from current page

### ISSUE THREAD

**Issue by bensmithgb53** [MarcellPerger1/adblock-bookmarklet#23] opened 2023-08-05 11:29 UTC
Hi, I'm trying to use this for chrome on my phone as I getting fed up with ads. Is there anyway to stop ads and redirect like new taps from opening by itself with pop up box coming up asking me if I want to leave current page I'm on? Make this as JavaScript bookmarklet.

**Comment by MarcellPerger1** [comment] 2023-08-06 19:29
Are you using it by setting it as a bookmark then clicking on it, or are you pasting it into the URL bar?

Also, did you use the `dist/release/bookmarklet.min.txt` file? That is the version that is marked as a javascript bookmarklet.

**Comment by bensmithgb53** [comment] 2023-08-08 11:46
> Are you using it by setting it as a bookmark then clicking on it, or are you pasting it into the URL bar?
> 
> Also, did you use the `dist/release/bookmarklet.min.txt` file? That is the version that is marked as a javascript bookmarklet.

I'm copying all text in dist/release/bookmarklet.min.txt and putting it into a bookmark when when I'm on website in the URL at the top of my phone I type in ads it comes up bookmark I click onto it and doesn't do anything but sometimes comes ads do go but I keep getting new taps opening up too.

**Comment by MarcellPerger1** [comment] 2023-08-09 05:47
For me, when I click on the bookmark like that, it removes the ads, and no new tabs open.

**Comment by MarcellPerger1** [comment] 2023-08-09 06:23
But I was able to reproduce this issue on Firefox for Android.

**Comment by MarcellPerger1** [comment] 2023-08-09 06:44
Does this issue still occur on the latest version for you? For me, it's fixed on Firefox for Android.

**Comment by MarcellPerger1** [comment] 2023-08-19 14:58
I'm going to close this to keep the issues tab tidy. If the issue is still happening, let me know.

**Closed by MarcellPerger1** 2023-08-19 14:58 UTC
Labels: status--need-more-info
